---
:ems:
  :ems_ansible_tower:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:http_proxy:
  :ansible_tower:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :ansible_tower_automation:
    :allow_targeted_refresh: true
    :inventory_collections:
      :saver_strategy: batch
:log:
  :level_ansible_tower: info
